import type { NormalizedSpec } from "@sdkparity/openapi";
import { codeModeExecuteInputSchema, codeModeExecuteResultSchema, mcpSearchInputSchema } from "./schemas.js";
import type { CodeModeExecuteInput, CodeModeExecuteResult, McpSearchInput, McpSearchResult } from "./schemas.js";

export function searchOperations(spec: NormalizedSpec, input: McpSearchInput): McpSearchResult[] {
  const parsed = mcpSearchInputSchema.parse(input);
  const query = parsed.query.toLowerCase();

  return spec.operations
    .filter((operation) =>
      [
        operation.operationId,
        operation.path,
        operation.method,
        operation.summary ?? "",
        operation.tags.join(" ")
      ]
        .join(" ")
        .toLowerCase()
        .includes(query)
    )
    .slice(0, parsed.limit)
    .map((operation) => ({
      operationId: operation.operationId,
      method: operation.method.toUpperCase(),
      path: operation.path,
      ...(operation.summary ? { summary: operation.summary } : {})
    }));
}

export function generateCodeModeTypes(spec: NormalizedSpec): string {
  const methods = spec.operations.map((operation) => {
    const methodName = operation.sdkName;
    const summary = operation.summary ? `  /** ${escapeComment(operation.summary)} */\n` : "";
    return `${summary}  ${methodName}(input: Record<string, unknown>): Promise<unknown>;`;
  });

  return [
    "/* Generated by SDK Parity. Credentials stay in the host runtime. */",
    "export type SdkParityApi = {",
    ...methods,
    "};",
    ""
  ].join("\n");
}

export function executeCodeModeDryRun(
  spec: NormalizedSpec,
  input: CodeModeExecuteInput
): CodeModeExecuteResult {
  const parsed = codeModeExecuteInputSchema.parse(input);
  const allowed = new Set(parsed.allowedOperationIds ?? spec.operations.map((operation) => operation.operationId));
  const calls = [...extractOperationNames(parsed.code)]
    .map((name) => spec.operations.find((operation) => operation.sdkName === name || operation.operationId === name))
    .filter((operation) => operation !== undefined)
    .filter((operation) => allowed.has(operation.operationId))
    .map((operation) => ({
      operationId: operation.operationId,
      method: operation.method.toUpperCase(),
      path: operation.path,
      dryRun: parsed.dryRun
    }));

  const diagnostics =
    calls.length === 0
      ? [
          {
            code: "no_operation_calls_detected",
            message: "No SDK Parity API operation calls were detected in the submitted Code Mode script."
          }
        ]
      : [];

  return codeModeExecuteResultSchema.parse({
    ok: diagnostics.length === 0,
    dryRun: parsed.dryRun,
    calls,
    diagnostics,
    output: parsed.dryRun
      ? `Dry run planned ${calls.length} call${calls.length === 1 ? "" : "s"}.`
      : "Execution is delegated to the hosted sandbox in production."
  });
}

function extractOperationNames(code: string): Set<string> {
  const names = new Set<string>();
  const patterns = [/\b(?:api|sdk|client)\.([A-Za-z_$][\w$]*)\s*\(/g, /\bexecute\(["']([A-Za-z0-9_:-]+)["']/g];

  for (const pattern of patterns) {
    for (const match of code.matchAll(pattern)) {
      const name = match[1];
      if (name) {
        names.add(name);
      }
    }
  }

  return names;
}

function escapeComment(value: string): string {
  return value.replace(/\*\//g, "* /");
}
